"""ORM models for the historical-intelligence domain.

Split into three tables per the design doc (§6.3): a session's feature vector,
its embedding/index reference, and its computed statistics are different
concerns with different update frequencies.

* **HistoricalSession**   — one trading day's market feature vector + the actual
  next-day outcome (the label used for statistics).
* **HistoricalEmbedding** — index membership metadata; the raw pre-normalized
  vector remains in ``HistoricalSession.feature_vector`` in PostgreSQL.
* **HistoricalIndexState**— the committed identity of the current corpus.
* **HistoricalStatistics**— statistics computed from the actual next-day outcomes
  of a query session's nearest neighbours (never generated by an LLM).
"""

from __future__ import annotations

from datetime import date, datetime, timezone

from sqlalchemy import (
    JSON,
    CheckConstraint,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.shared.database import Base


def _utcnow() -> datetime:
    return datetime.now(tz=timezone.utc)


class HistoricalSession(Base):
    __tablename__ = "historical_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    date: Mapped[date] = mapped_column(Date, unique=True, index=True, nullable=False)

    # Readable summary columns (also present inside feature_vector).
    avg_return: Mapped[float] = mapped_column(Float, nullable=False)
    median_return: Mapped[float] = mapped_column(Float, nullable=False)
    pct_advancers: Mapped[float] = mapped_column(Float, nullable=False)
    advance_decline_ratio: Mapped[float] = mapped_column(Float, nullable=False)
    avg_rsi: Mapped[float] = mapped_column(Float, nullable=False)

    # The full normalized-input feature dict (raw, pre-normalization values).
    feature_vector: Mapped[dict] = mapped_column(JSON, nullable=False)

    # Outcome (the label): next trading session's market average return.
    next_day_return: Mapped[float | None] = mapped_column(Float)
    outcome: Mapped[str | None] = mapped_column(String(10))  # bullish/bearish/neutral

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        server_default=func.now(),
        nullable=False,
    )

    embedding: Mapped["HistoricalEmbedding | None"] = relationship(
        back_populates="session", uselist=False, cascade="all, delete-orphan"
    )
    statistics: Mapped["HistoricalStatistics | None"] = relationship(
        back_populates="session", uselist=False, cascade="all, delete-orphan"
    )


class HistoricalEmbedding(Base):
    __tablename__ = "historical_embeddings"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[int] = mapped_column(
        ForeignKey("historical_sessions.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    # The id used for this vector inside the FAISS IndexIDMap (== session_id).
    faiss_id: Mapped[int] = mapped_column(Integer, index=True, nullable=False)
    dim: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        server_default=func.now(),
        nullable=False,
    )

    session: Mapped["HistoricalSession"] = relationship(back_populates="embedding")


class HistoricalIndexState(Base):
    """Committed identity of the corpus represented by the current index.

    PostgreSQL owns this state and the raw vectors.  FAISS files are only a
    reconstructable local cache of this committed generation.
    """

    __tablename__ = "historical_index_state"
    __table_args__ = (CheckConstraint("id = 1", name="ck_history_index_state_singleton"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=1)
    corpus_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    session_count: Mapped[int] = mapped_column(Integer, nullable=False)
    dimension: Mapped[int] = mapped_column(Integer, nullable=False)
    artifact_schema_version: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )
    built_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        onupdate=_utcnow,
        server_default=func.now(),
        nullable=False,
    )


class HistoricalStatistics(Base):
    __tablename__ = "historical_statistics"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[int] = mapped_column(
        ForeignKey("historical_sessions.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    k: Mapped[int] = mapped_column(Integer, nullable=False)
    sample_size: Mapped[int] = mapped_column(Integer, nullable=False)

    bullish_count: Mapped[int] = mapped_column(Integer, nullable=False)
    bearish_count: Mapped[int] = mapped_column(Integer, nullable=False)
    neutral_count: Mapped[int] = mapped_column(Integer, nullable=False)
    bullish_probability: Mapped[float | None] = mapped_column(Float)

    avg_next_day_return: Mapped[float | None] = mapped_column(Float)
    median_next_day_return: Mapped[float | None] = mapped_column(Float)
    std_next_day_return: Mapped[float | None] = mapped_column(Float)
    best_case_return: Mapped[float | None] = mapped_column(Float)
    worst_case_return: Mapped[float | None] = mapped_column(Float)
    ci_low: Mapped[float | None] = mapped_column(Float)
    ci_high: Mapped[float | None] = mapped_column(Float)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        server_default=func.now(),
        nullable=False,
    )

    session: Mapped["HistoricalSession"] = relationship(back_populates="statistics")
