"use client";

import { useState, type FormEvent } from "react";

import { DataTable, type Column } from "@/components/DataTable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { DataState, Panel, SectionHeader, TrendValue } from "@/components/workspace";
import type { HoldingRiskContribution, PortfolioCounterfactual, PortfolioRisk, SectorDeviation } from "@/lib/api";

const display = (value: number | null, suffix = "") => value == null ? "Unavailable" : `${value.toFixed(2)}${suffix}`;
const signed = (value: number | null) => value == null ? "Unavailable" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;

function CorrelationHeatmap({ risk }: { risk: PortfolioRisk }) {
  const symbols = [...new Set(risk.correlation.map((item) => item.symbol_x))];
  const lookup = new Map(risk.correlation.map((item) => [`${item.symbol_x}:${item.symbol_y}`, item]));
  return <div className="overflow-x-auto"><table className="min-w-max text-center text-xs"><caption className="sr-only">Holding return correlation heatmap</caption><thead><tr><th className="p-1.5 text-left">Symbol</th>{symbols.map((symbol) => <th key={symbol} className="p-1.5">{symbol.replace(".NS", "")}</th>)}</tr></thead><tbody>{symbols.map((row) => <tr key={row}><th className="p-1.5 text-left font-medium">{row.replace(".NS", "")}</th>{symbols.map((column) => { const value = lookup.get(`${row}:${column}`)?.correlation ?? null; const intensity = value == null ? 0 : Math.abs(value); return <td key={column} className="p-1"><span title={`${row} / ${column}: ${value == null ? "unavailable" : value.toFixed(2)}`} className="grid size-10 place-items-center rounded text-[10px] font-medium" style={{ backgroundColor: value == null ? "var(--muted)" : value >= 0 ? `color-mix(in srgb, var(--positive) ${20 + intensity * 55}%, transparent)` : `color-mix(in srgb, var(--negative) ${20 + intensity * 55}%, transparent)` }}>{value == null ? "—" : value.toFixed(2)}</span></td>; })}</tr>)}</tbody></table></div>;
}

const contributionColumns: Column<HoldingRiskContribution>[] = [
  { key: "symbol", header: "Holding", render: (row) => <span className="font-medium">{row.symbol}</span> },
  { key: "weight", header: "Weight", align: "right", render: (row) => `${row.weight_percent.toFixed(1)}%` },
  { key: "return", header: "Return contrib.", align: "right", render: (row) => <TrendValue value={row.return_contribution_percent}>{signed(row.return_contribution_percent)}</TrendValue> },
  { key: "risk", header: "Risk contrib.", align: "right", render: (row) => display(row.risk_contribution_percent, "%") },
  { key: "momentum", header: "20D momentum", align: "right", render: (row) => <TrendValue value={row.momentum_20d_percent}>{signed(row.momentum_20d_percent)}</TrendValue> },
];
const sectorColumns: Column<SectorDeviation>[] = [
  { key: "sector", header: "Sector", render: (row) => row.sector },
  { key: "portfolio", header: "Portfolio", align: "right", render: (row) => `${row.portfolio_weight_percent.toFixed(1)}%` },
  { key: "benchmark", header: "NIFTY 100", align: "right", render: (row) => `${row.benchmark_weight_percent.toFixed(1)}%` },
  { key: "deviation", header: "Deviation", align: "right", render: (row) => <TrendValue value={row.deviation_percent}>{signed(row.deviation_percent)}</TrendValue> },
];

export function PortfolioRiskView({ risk, onCounterfactual }: { risk: PortfolioRisk; onCounterfactual: (changes: { symbol: string; quantity_delta: number }[]) => Promise<PortfolioCounterfactual> }) {
  const [reduceSymbol, setReduceSymbol] = useState(""); const [reduceQty, setReduceQty] = useState("");
  const [addSymbol, setAddSymbol] = useState(""); const [addQty, setAddQty] = useState("");
  const [scenario, setScenario] = useState<PortfolioCounterfactual | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); const changes = []; if (reduceSymbol && Number(reduceQty) > 0) changes.push({ symbol: reduceSymbol.trim().toUpperCase(), quantity_delta: -Number(reduceQty) }); if (addSymbol && Number(addQty) > 0) changes.push({ symbol: addSymbol.trim().toUpperCase(), quantity_delta: Number(addQty) }); try { setScenario(await onCounterfactual(changes)); } catch { setError("The counterfactual could not be evaluated. Check quantities and tracked symbols."); } finally { setBusy(false); } }
  if (!risk.data_complete) return <Panel><SectionHeader title="Advanced risk diagnostics" description={risk.methodology} /><div className="mt-4"><DataState kind="unavailable" title="Risk history is incomplete" description={`At least ${risk.minimum_observations} aligned sessions are required. Missing or short history: ${risk.missing_symbols.join(", ") || "benchmark"}.`} /></div></Panel>;
  return <section aria-label="Advanced portfolio risk" className="space-y-5">
    <Panel><SectionHeader title="Advanced risk diagnostics" description={risk.methodology} /><div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["Beta", display(risk.beta)], ["Annual volatility", display(risk.annualized_volatility_percent, "%")], ["Sharpe", display(risk.sharpe_ratio)], ["Max drawdown", display(risk.max_drawdown_percent, "%")], ["Concentration HHI", display(risk.concentration_hhi)], ["Momentum exposure", signed(risk.momentum_exposure_percent)]].map(([label, value]) => <div key={label} className="rounded-lg border border-border/60 bg-muted/20 p-3"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold tabular-nums">{value}</p></div>)}</div><p className="mt-3 text-xs text-muted-foreground">{risk.observations} aligned sessions through {risk.as_of ?? "unavailable"}; Sharpe uses a zero risk-free-rate assumption.</p></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel><SectionHeader title="Correlation" description="Pairwise daily-close return correlation; unavailable cells have insufficient variance or history." /><div className="mt-3"><CorrelationHeatmap risk={risk} /></div></Panel><Panel><SectionHeader title="Regime sensitivity" description="Static-weight daily outcomes grouped by market_regime_v1 breadth context." /><div className="mt-3 space-y-2">{risk.regime_sensitivity.map((item) => <div key={item.regime} className="flex items-center justify-between rounded-lg border border-border/60 p-2.5 text-xs"><span className="capitalize">{item.regime.replaceAll("_", " ")} · {item.sessions} sessions</span><span className="tabular-nums"><TrendValue value={item.average_daily_return_percent}>{signed(item.average_daily_return_percent)}</TrendValue> · {item.positive_session_percent.toFixed(0)}% positive</span></div>)}</div></Panel></div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel><SectionHeader title="Holding contribution" description="Return and covariance-based risk contribution under current static weights." /><div className="mt-3"><DataTable columns={contributionColumns} rows={risk.holding_contributions} rowKey={(row) => row.symbol} /></div></Panel><Panel><SectionHeader title="Sector deviation" description={risk.sector_benchmark_methodology} /><div className="mt-3"><DataTable columns={sectorColumns} rows={risk.sector_deviation} rowKey={(row) => row.sector} /></div></Panel></div>
    <Panel><SectionHeader title="Stress scenarios" description="Deterministic scenario estimates using stated linear assumptions—not predictions." /><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{risk.stress_scenarios.map((item) => <article key={item.code} className="rounded-lg border border-border/60 bg-muted/20 p-3"><p className="text-xs font-semibold">{item.label}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-muted-foreground">{item.shock}</p><p className="mt-3 text-lg font-semibold tabular-nums"><TrendValue value={item.estimated_impact_percent}>{signed(item.estimated_impact_percent)}</TrendValue></p><p className="mt-2 text-[10px] leading-4 text-muted-foreground">{item.methodology}</p></article>)}</div></Panel>
    <Panel><SectionHeader title="Counterfactual portfolio" description="Estimate what changes if you reduce one holding and add another. No holdings are modified." /><form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5 lg:items-end"><div><Label htmlFor="reduce-symbol">Reduce symbol</Label><Input id="reduce-symbol" value={reduceSymbol} onChange={(event) => setReduceSymbol(event.target.value)} placeholder="SBIN.NS" /></div><div><Label htmlFor="reduce-qty">Reduce quantity</Label><Input id="reduce-qty" type="number" min="0" step="any" value={reduceQty} onChange={(event) => setReduceQty(event.target.value)} /></div><div><Label htmlFor="add-symbol">Add symbol</Label><Input id="add-symbol" value={addSymbol} onChange={(event) => setAddSymbol(event.target.value)} placeholder="TCS.NS" /></div><div><Label htmlFor="add-qty">Add quantity</Label><Input id="add-qty" type="number" min="0" step="any" value={addQty} onChange={(event) => setAddQty(event.target.value)} /></div><Button type="submit" disabled={busy || (!reduceSymbol && !addSymbol)}>{busy ? "Estimating…" : "Compare scenario"}</Button></form>{error && <p role="alert" className="mt-3 text-sm text-negative">{error}</p>}{scenario && <div className="mt-4"><p className="mb-3 text-xs font-medium text-warning">{scenario.label}</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(scenario.deltas).map(([key, value]) => <div key={key} className="rounded-lg border border-border/60 p-3"><p className="text-[10px] capitalize text-muted-foreground">{key.replaceAll("_", " ")}</p><p className="mt-1 text-sm font-semibold tabular-nums">{value == null ? "Unavailable" : `${value >= 0 ? "+" : ""}${value.toFixed(3)}`}</p></div>)}</div></div>}</Panel>
  </section>;
}
