"""historical intelligence tables

Revision ID: 0005_history
Revises: 0004_portfolio
Create Date: 2026-08-04 15:33:35.446811
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0005_history'
down_revision: str | None = '0004_portfolio'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_return', sa.Float(), nullable=False),
    sa.Column('median_return', sa.Float(), nullable=False),
    sa.Column('pct_advancers', sa.Float(), nullable=False),
    sa.Column('advance_decline_ratio', sa.Float(), nullable=False),
    sa.Column('avg_rsi', sa.Float(), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('next_day_return', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_sessions_date'), 'historical_sessions', ['date'], unique=True)
    op.create_table('historical_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('faiss_id', sa.Integer(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['historical_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_embeddings_faiss_id'), 'historical_embeddings', ['faiss_id'], unique=False)
    op.create_index(op.f('ix_historical_embeddings_session_id'), 'historical_embeddings', ['session_id'], unique=True)
    op.create_table('historical_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('bullish_count', sa.Integer(), nullable=False),
    sa.Column('bearish_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('bullish_probability', sa.Float(), nullable=True),
    sa.Column('avg_next_day_return', sa.Float(), nullable=True),
    sa.Column('median_next_day_return', sa.Float(), nullable=True),
    sa.Column('std_next_day_return', sa.Float(), nullable=True),
    sa.Column('best_case_return', sa.Float(), nullable=True),
    sa.Column('worst_case_return', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['historical_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_statistics_session_id'), 'historical_statistics', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_statistics_session_id'), table_name='historical_statistics')
    op.drop_table('historical_statistics')
    op.drop_index(op.f('ix_historical_embeddings_session_id'), table_name='historical_embeddings')
    op.drop_index(op.f('ix_historical_embeddings_faiss_id'), table_name='historical_embeddings')
    op.drop_table('historical_embeddings')
    op.drop_index(op.f('ix_historical_sessions_date'), table_name='historical_sessions')
    op.drop_table('historical_sessions')
    # ### end Alembic commands ###
