"""news and sentiment tables

Revision ID: 0006_news
Revises: 0005_history
Create Date: 2026-08-04 16:08:36.841631
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0006_news'
down_revision: str | None = '0005_history'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_positive', sa.Float(), nullable=False),
    sa.Column('sentiment_negative', sa.Float(), nullable=False),
    sa.Column('sentiment_neutral', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_table('news_article_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'stock_id', name='uq_news_article_stock')
    )
    op.create_index(op.f('ix_news_article_stocks_article_id'), 'news_article_stocks', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_article_stocks_stock_id'), 'news_article_stocks', ['stock_id'], unique=False)
    op.create_table('sentiment_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_sentiment_daily_stock_date')
    )
    op.create_index(op.f('ix_sentiment_daily_date'), 'sentiment_daily', ['date'], unique=False)
    op.create_index(op.f('ix_sentiment_daily_stock_id'), 'sentiment_daily', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_daily_stock_id'), table_name='sentiment_daily')
    op.drop_index(op.f('ix_sentiment_daily_date'), table_name='sentiment_daily')
    op.drop_table('sentiment_daily')
    op.drop_index(op.f('ix_news_article_stocks_stock_id'), table_name='news_article_stocks')
    op.drop_index(op.f('ix_news_article_stocks_article_id'), table_name='news_article_stocks')
    op.drop_table('news_article_stocks')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
